### ISSUE TITLE
No make file in the spades_src folder

### ISSUE THREAD

**Issue by jianshu93** [cwright7101/mulksg#1]
I cannot build it as you suggested. I also try to make in the assembler folder but it gave error: 

make -C build/release/projects/spades
make[1]: *** build/release/projects/spades: No such file or directory.  Stop.
makefile:4: recipe for target 'rd' failed
make: *** [rd] Error 2

Can you please help? How can I successfully install mulksg?

**Comment by cwright7101** [comment]
I have uploaded the makefile in the spades_src directory, it was missing before. Thanks for the issue!
